/**
 * This file was generated automatically by Supernova.io and should not be changed manually.
 * To modify the format or content of this file, please contact your design system team. 
 */

import { StringTokens } from "./string";

const fontWeightTypographyDisplayLargeFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyDisplayLargeMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyDisplayDefaultFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyMetaDefaultSentenceCaseFontWeight = StringTokens.stringTypographyFontWeightMedium;
const fontWeightTypographyHeadlineLargeFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyTitleXlargeFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyLabelLargeFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodyXlargeFontWeight = StringTokens.stringTypographyFontWeightRegular;
const fontWeightTypographyMetaLargeFontWeight = StringTokens.stringTypographyFontWeightMedium;
const fontWeightTypographyMetaDefaultFontWeight = StringTokens.stringTypographyFontWeightMedium;
const fontWeightTypographyMetaSmallFontWeight = StringTokens.stringTypographyFontWeightMedium;
const fontWeightTypographyBodyXlargeLinkFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodyXlargeStrongFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodyLargeFontWeight = StringTokens.stringTypographyFontWeightRegular;
const fontWeightTypographyBodyLargeStrongFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodyLargeLinkFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodyDefaultFontWeight = StringTokens.stringTypographyFontWeightRegular;
const fontWeightTypographyBodyDefaultStrongFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodyDefaultLinkFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodySmallFontWeight = StringTokens.stringTypographyFontWeightRegular;
const fontWeightTypographyBodySmallStrongFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyBodySmallLinkFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyLabelDefaultFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyLabelSmallFontWeight = StringTokens.stringTypographyFontWeightSemibold;
const fontWeightTypographyTitleXlargeMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyTitleLargeFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyTitleLargeMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyTitleDefaultFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyTitleDefaultMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyTitleSmallFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyTitleSmallMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyHeadlineLargeMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyHeadlineDefaultFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyHeadlineDefaultMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyHeadlineSmallFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyHeadlineSmallMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyHeadlineXsmallFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyHeadlineXsmallMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyDisplayDefaultMobileFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyDisplaySmallFontWeight = StringTokens.stringTypographyFontWeightBold;
const fontWeightTypographyDisplaySmallMobileFontWeight = StringTokens.stringTypographyFontWeightBold;

export const FontWeightTokens = {
  fontWeightTypographyDisplayLargeFontWeight,
  fontWeightTypographyDisplayLargeMobileFontWeight,
  fontWeightTypographyDisplayDefaultFontWeight,
  fontWeightTypographyMetaDefaultSentenceCaseFontWeight,
  fontWeightTypographyHeadlineLargeFontWeight,
  fontWeightTypographyTitleXlargeFontWeight,
  fontWeightTypographyLabelLargeFontWeight,
  fontWeightTypographyBodyXlargeFontWeight,
  fontWeightTypographyMetaLargeFontWeight,
  fontWeightTypographyMetaDefaultFontWeight,
  fontWeightTypographyMetaSmallFontWeight,
  fontWeightTypographyBodyXlargeLinkFontWeight,
  fontWeightTypographyBodyXlargeStrongFontWeight,
  fontWeightTypographyBodyLargeFontWeight,
  fontWeightTypographyBodyLargeStrongFontWeight,
  fontWeightTypographyBodyLargeLinkFontWeight,
  fontWeightTypographyBodyDefaultFontWeight,
  fontWeightTypographyBodyDefaultStrongFontWeight,
  fontWeightTypographyBodyDefaultLinkFontWeight,
  fontWeightTypographyBodySmallFontWeight,
  fontWeightTypographyBodySmallStrongFontWeight,
  fontWeightTypographyBodySmallLinkFontWeight,
  fontWeightTypographyLabelDefaultFontWeight,
  fontWeightTypographyLabelSmallFontWeight,
  fontWeightTypographyTitleXlargeMobileFontWeight,
  fontWeightTypographyTitleLargeFontWeight,
  fontWeightTypographyTitleLargeMobileFontWeight,
  fontWeightTypographyTitleDefaultFontWeight,
  fontWeightTypographyTitleDefaultMobileFontWeight,
  fontWeightTypographyTitleSmallFontWeight,
  fontWeightTypographyTitleSmallMobileFontWeight,
  fontWeightTypographyHeadlineLargeMobileFontWeight,
  fontWeightTypographyHeadlineDefaultFontWeight,
  fontWeightTypographyHeadlineDefaultMobileFontWeight,
  fontWeightTypographyHeadlineSmallFontWeight,
  fontWeightTypographyHeadlineSmallMobileFontWeight,
  fontWeightTypographyHeadlineXsmallFontWeight,
  fontWeightTypographyHeadlineXsmallMobileFontWeight,
  fontWeightTypographyDisplayDefaultMobileFontWeight,
  fontWeightTypographyDisplaySmallFontWeight,
  fontWeightTypographyDisplaySmallMobileFontWeight,
}