/**
 * This file was generated automatically by Supernova.io and should not be changed manually.
 * To modify the format or content of this file, please contact your design system team. 
 */

import { DimensionTokens } from "./dimension";

const letterSpacingTypographyDisplayLargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacing2xsmall;
const letterSpacingTypographyDisplayLargeMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacing2xsmall;
const letterSpacingTypographyDisplayDefaultLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacing2xsmall;
const letterSpacingTypographyMetaDefaultSentenceCaseLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingMedium;
const letterSpacingTypographyBodyXlargeLinkLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyHeadlineLargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingXsmall;
const letterSpacingTypographyTitleXlargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyLabelLargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodyXlargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyMetaLargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingMedium;
const letterSpacingTypographyMetaDefaultLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingMedium;
const letterSpacingTypographyMetaSmallLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingMedium;
const letterSpacingTypographyBodyXlargeStrongLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodyLargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodyLargeStrongLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodyLargeLinkLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodyDefaultLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodyDefaultStrongLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodyDefaultLinkLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodySmallLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodySmallStrongLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyBodySmallLinkLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyLabelDefaultLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyLabelSmallLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyTitleXlargeMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyTitleLargeLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyTitleLargeMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyTitleDefaultLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyTitleDefaultMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyTitleSmallLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyTitleSmallMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyHeadlineLargeMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingXsmall;
const letterSpacingTypographyHeadlineDefaultLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingSmall;
const letterSpacingTypographyHeadlineDefaultMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingSmall;
const letterSpacingTypographyHeadlineSmallLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyHeadlineSmallMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyHeadlineXsmallLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyHeadlineXsmallMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingDefault;
const letterSpacingTypographyDisplayDefaultMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacing2xsmall;
const letterSpacingTypographyDisplaySmallLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingXsmall;
const letterSpacingTypographyDisplaySmallMobileLetterSpacing = DimensionTokens.dimensionTypographyLetterSpacingXsmall;

export const LetterSpacingTokens = {
  letterSpacingTypographyDisplayLargeLetterSpacing,
  letterSpacingTypographyDisplayLargeMobileLetterSpacing,
  letterSpacingTypographyDisplayDefaultLetterSpacing,
  letterSpacingTypographyMetaDefaultSentenceCaseLetterSpacing,
  letterSpacingTypographyBodyXlargeLinkLetterSpacing,
  letterSpacingTypographyHeadlineLargeLetterSpacing,
  letterSpacingTypographyTitleXlargeLetterSpacing,
  letterSpacingTypographyLabelLargeLetterSpacing,
  letterSpacingTypographyBodyXlargeLetterSpacing,
  letterSpacingTypographyMetaLargeLetterSpacing,
  letterSpacingTypographyMetaDefaultLetterSpacing,
  letterSpacingTypographyMetaSmallLetterSpacing,
  letterSpacingTypographyBodyXlargeStrongLetterSpacing,
  letterSpacingTypographyBodyLargeLetterSpacing,
  letterSpacingTypographyBodyLargeStrongLetterSpacing,
  letterSpacingTypographyBodyLargeLinkLetterSpacing,
  letterSpacingTypographyBodyDefaultLetterSpacing,
  letterSpacingTypographyBodyDefaultStrongLetterSpacing,
  letterSpacingTypographyBodyDefaultLinkLetterSpacing,
  letterSpacingTypographyBodySmallLetterSpacing,
  letterSpacingTypographyBodySmallStrongLetterSpacing,
  letterSpacingTypographyBodySmallLinkLetterSpacing,
  letterSpacingTypographyLabelDefaultLetterSpacing,
  letterSpacingTypographyLabelSmallLetterSpacing,
  letterSpacingTypographyTitleXlargeMobileLetterSpacing,
  letterSpacingTypographyTitleLargeLetterSpacing,
  letterSpacingTypographyTitleLargeMobileLetterSpacing,
  letterSpacingTypographyTitleDefaultLetterSpacing,
  letterSpacingTypographyTitleDefaultMobileLetterSpacing,
  letterSpacingTypographyTitleSmallLetterSpacing,
  letterSpacingTypographyTitleSmallMobileLetterSpacing,
  letterSpacingTypographyHeadlineLargeMobileLetterSpacing,
  letterSpacingTypographyHeadlineDefaultLetterSpacing,
  letterSpacingTypographyHeadlineDefaultMobileLetterSpacing,
  letterSpacingTypographyHeadlineSmallLetterSpacing,
  letterSpacingTypographyHeadlineSmallMobileLetterSpacing,
  letterSpacingTypographyHeadlineXsmallLetterSpacing,
  letterSpacingTypographyHeadlineXsmallMobileLetterSpacing,
  letterSpacingTypographyDisplayDefaultMobileLetterSpacing,
  letterSpacingTypographyDisplaySmallLetterSpacing,
  letterSpacingTypographyDisplaySmallMobileLetterSpacing,
}