/**
 * This file was generated automatically by Supernova.io and should not be changed manually.
 * To modify the format or content of this file, please contact your design system team. 
 */

import { DimensionTokens } from "./dimension";

const lineHeightTypographyDisplayLargeLineHeight = DimensionTokens.dimensionTypographyLineHeight108;
const lineHeightTypographyDisplayLargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyDisplayLargeMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight96;
const lineHeightTypographyDisplayLargeMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyDisplayDefaultLineHeight = DimensionTokens.dimensionTypographyLineHeight80;
const lineHeightTypographyDisplayDefaultParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyMetaDefaultSentenceCaseLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyMetaDefaultSentenceCaseParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyXlargeLinkLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyBodyXlargeLinkParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyDisplayDefaultMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight72;
const lineHeightTypographyDisplayDefaultMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyDisplaySmallLineHeight = DimensionTokens.dimensionTypographyLineHeight64;
const lineHeightTypographyDisplaySmallMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight56;
const lineHeightTypographyDisplaySmallParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyDisplaySmallMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineLargeLineHeight = DimensionTokens.dimensionTypographyLineHeight64;
const lineHeightTypographyHeadlineLargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineLargeMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight56;
const lineHeightTypographyHeadlineLargeMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineDefaultLineHeight = DimensionTokens.dimensionTypographyLineHeight56;
const lineHeightTypographyHeadlineDefaultMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyHeadlineDefaultParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineSmallLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyHeadlineSmallParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineSmallMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyHeadlineSmallMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineXsmallLineHeight = DimensionTokens.dimensionTypographyLineHeight32;
const lineHeightTypographyHeadlineXsmallParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineXsmallMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight32;
const lineHeightTypographyHeadlineXsmallMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyHeadlineDefaultMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleXlargeLineHeight = DimensionTokens.dimensionTypographyLineHeight56;
const lineHeightTypographyTitleXlargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleXlargeMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyTitleXlargeMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleLargeLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyTitleLargeMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight32;
const lineHeightTypographyTitleLargeMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleLargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleDefaultLineHeight = DimensionTokens.dimensionTypographyLineHeight32;
const lineHeightTypographyTitleDefaultMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyTitleDefaultParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleDefaultMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleSmallLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyTitleSmallParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyTitleSmallMobileLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyLabelLargeLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyTitleSmallMobileParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyLabelLargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyLabelDefaultLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyLabelSmallLineHeight = DimensionTokens.dimensionTypographyLineHeight16;
const lineHeightTypographyLabelDefaultParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyXlargeLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyLabelSmallParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyXlargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyXlargeStrongLineHeight = DimensionTokens.dimensionTypographyLineHeight40;
const lineHeightTypographyBodyXlargeStrongParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyLargeLineHeight = DimensionTokens.dimensionTypographyLineHeight32;
const lineHeightTypographyBodyLargeStrongLineHeight = DimensionTokens.dimensionTypographyLineHeight32;
const lineHeightTypographyBodyLargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyLargeLinkLineHeight = DimensionTokens.dimensionTypographyLineHeight32;
const lineHeightTypographyBodyLargeLinkParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyLargeStrongParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyDefaultLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyBodyDefaultParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyDefaultStrongLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyBodyDefaultStrongParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodyDefaultLinkLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyBodyDefaultLinkParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodySmallLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyBodySmallParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodySmallStrongLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyBodySmallLinkLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyBodySmallStrongParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyBodySmallLinkParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyMetaLargeLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyMetaLargeParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyMetaDefaultLineHeight = DimensionTokens.dimensionTypographyLineHeight24;
const lineHeightTypographyMetaDefaultParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;
const lineHeightTypographyMetaSmallLineHeight = DimensionTokens.dimensionTypographyLineHeight16;
const lineHeightTypographyMetaSmallParagraphSpacing = DimensionTokens.dimensionTypographyParagraphSpacing0;

export const LineHeightTokens = {
  lineHeightTypographyDisplayLargeLineHeight,
  lineHeightTypographyDisplayLargeParagraphSpacing,
  lineHeightTypographyDisplayLargeMobileLineHeight,
  lineHeightTypographyDisplayLargeMobileParagraphSpacing,
  lineHeightTypographyDisplayDefaultLineHeight,
  lineHeightTypographyDisplayDefaultParagraphSpacing,
  lineHeightTypographyMetaDefaultSentenceCaseLineHeight,
  lineHeightTypographyMetaDefaultSentenceCaseParagraphSpacing,
  lineHeightTypographyBodyXlargeLinkLineHeight,
  lineHeightTypographyBodyXlargeLinkParagraphSpacing,
  lineHeightTypographyDisplayDefaultMobileLineHeight,
  lineHeightTypographyDisplayDefaultMobileParagraphSpacing,
  lineHeightTypographyDisplaySmallLineHeight,
  lineHeightTypographyDisplaySmallMobileLineHeight,
  lineHeightTypographyDisplaySmallParagraphSpacing,
  lineHeightTypographyDisplaySmallMobileParagraphSpacing,
  lineHeightTypographyHeadlineLargeLineHeight,
  lineHeightTypographyHeadlineLargeParagraphSpacing,
  lineHeightTypographyHeadlineLargeMobileLineHeight,
  lineHeightTypographyHeadlineLargeMobileParagraphSpacing,
  lineHeightTypographyHeadlineDefaultLineHeight,
  lineHeightTypographyHeadlineDefaultMobileLineHeight,
  lineHeightTypographyHeadlineDefaultParagraphSpacing,
  lineHeightTypographyHeadlineSmallLineHeight,
  lineHeightTypographyHeadlineSmallParagraphSpacing,
  lineHeightTypographyHeadlineSmallMobileLineHeight,
  lineHeightTypographyHeadlineSmallMobileParagraphSpacing,
  lineHeightTypographyHeadlineXsmallLineHeight,
  lineHeightTypographyHeadlineXsmallParagraphSpacing,
  lineHeightTypographyHeadlineXsmallMobileLineHeight,
  lineHeightTypographyHeadlineXsmallMobileParagraphSpacing,
  lineHeightTypographyHeadlineDefaultMobileParagraphSpacing,
  lineHeightTypographyTitleXlargeLineHeight,
  lineHeightTypographyTitleXlargeParagraphSpacing,
  lineHeightTypographyTitleXlargeMobileLineHeight,
  lineHeightTypographyTitleXlargeMobileParagraphSpacing,
  lineHeightTypographyTitleLargeLineHeight,
  lineHeightTypographyTitleLargeMobileLineHeight,
  lineHeightTypographyTitleLargeMobileParagraphSpacing,
  lineHeightTypographyTitleLargeParagraphSpacing,
  lineHeightTypographyTitleDefaultLineHeight,
  lineHeightTypographyTitleDefaultMobileLineHeight,
  lineHeightTypographyTitleDefaultParagraphSpacing,
  lineHeightTypographyTitleDefaultMobileParagraphSpacing,
  lineHeightTypographyTitleSmallLineHeight,
  lineHeightTypographyTitleSmallParagraphSpacing,
  lineHeightTypographyTitleSmallMobileLineHeight,
  lineHeightTypographyLabelLargeLineHeight,
  lineHeightTypographyTitleSmallMobileParagraphSpacing,
  lineHeightTypographyLabelLargeParagraphSpacing,
  lineHeightTypographyLabelDefaultLineHeight,
  lineHeightTypographyLabelSmallLineHeight,
  lineHeightTypographyLabelDefaultParagraphSpacing,
  lineHeightTypographyBodyXlargeLineHeight,
  lineHeightTypographyLabelSmallParagraphSpacing,
  lineHeightTypographyBodyXlargeParagraphSpacing,
  lineHeightTypographyBodyXlargeStrongLineHeight,
  lineHeightTypographyBodyXlargeStrongParagraphSpacing,
  lineHeightTypographyBodyLargeLineHeight,
  lineHeightTypographyBodyLargeStrongLineHeight,
  lineHeightTypographyBodyLargeParagraphSpacing,
  lineHeightTypographyBodyLargeLinkLineHeight,
  lineHeightTypographyBodyLargeLinkParagraphSpacing,
  lineHeightTypographyBodyLargeStrongParagraphSpacing,
  lineHeightTypographyBodyDefaultLineHeight,
  lineHeightTypographyBodyDefaultParagraphSpacing,
  lineHeightTypographyBodyDefaultStrongLineHeight,
  lineHeightTypographyBodyDefaultStrongParagraphSpacing,
  lineHeightTypographyBodyDefaultLinkLineHeight,
  lineHeightTypographyBodyDefaultLinkParagraphSpacing,
  lineHeightTypographyBodySmallLineHeight,
  lineHeightTypographyBodySmallParagraphSpacing,
  lineHeightTypographyBodySmallStrongLineHeight,
  lineHeightTypographyBodySmallLinkLineHeight,
  lineHeightTypographyBodySmallStrongParagraphSpacing,
  lineHeightTypographyBodySmallLinkParagraphSpacing,
  lineHeightTypographyMetaLargeLineHeight,
  lineHeightTypographyMetaLargeParagraphSpacing,
  lineHeightTypographyMetaDefaultLineHeight,
  lineHeightTypographyMetaDefaultParagraphSpacing,
  lineHeightTypographyMetaSmallLineHeight,
  lineHeightTypographyMetaSmallParagraphSpacing,
}